# Generated by Django 5.2.6 on 2025-09-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AddField(
            model_name='contact',
            name='is_readed',
            field=models.BooleanField(default=False, verbose_name='خوانده شده خوانده نشده'),
        ),
    ]
