# Generated by Django 5.2.6 on 2025-09-17 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0005_rename_comment_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'کامنت مقالات', 'verbose_name_plural': 'کامنت های مقالات'},
        ),
    ]
