# Generated by Django 5.2.6 on 2025-09-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_module', '0006_alter_articlecomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
