# Generated by Django 5.2.6 on 2025-09-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'رنگ بندی',
                'verbose_name_plural': 'رنگ بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('body', models.TextField(verbose_name='توضیحات محصولات')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='آدرس')),
                ('price', models.IntegerField(max_length=10, verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='products', verbose_name='تصویر')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_active', models.BooleanField(verbose_name='فعال / غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('color', models.ManyToManyField(related_name='products', to='shop_module.color', verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
