# Generated by Django 5.2.6 on 2025-09-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
