# Generated by Django 5.2.6 on 2025-09-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productkeyfeature',
            name='status',
        ),
        migrations.CreateModel(
            name='ProductAdditionalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductAdditionalInformations', to='shop_module.product', verbose_name='اطلاعات اضافی')),
            ],
        ),
    ]
