# Generated by Django 5.2.4 on 2025-09-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKeyFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان')),
                ('status', models.BooleanField(verbose_name='نکته مثبت / نکته منفی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_module.product', verbose_name='محصول')),
            ],
        ),
    ]
