# Generated by Django 5.2.6 on 2025-09-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0002_remove_productkeyfeature_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productadditionalinformation',
            options={'verbose_name': 'اطلاعات اضافی', 'verbose_name_plural': 'اطلاعات اضافی'},
        ),
        migrations.AlterField(
            model_name='productadditionalinformation',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
    ]
