# Generated by Django 5.2.4 on 2025-09-28 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0003_productkeyfeatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productkeyfeatures',
            options={'verbose_name': 'ویژگی های محصول', 'verbose_name_plural': 'ویژگی های محصولات'},
        ),
        migrations.AlterField(
            model_name='productkeyfeatures',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='shop_module.product', verbose_name='محصول'),
        ),
    ]
