# Generated by Django 5.2.6 on 2025-10-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='آدرس محل سکونت'),
        ),
    ]
