# Generated by Django 5.2.6 on 2025-09-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0003_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='user_avatar/unknown-user.png', null=True, upload_to='user_avatar', verbose_name='آواتار'),
        ),
    ]
