# Generated by Django 5.2.6 on 2025-09-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatar', verbose_name='آواتار'),
        ),
    ]
